sudo: false
language: perl
perl:
    - "5.20-shrplib"
    - "5.18-shrplib"
    - "system-perl"
env:
    - CC=clang
    - CC=gcc

addons:
    apt:
        packages:
            - libperl-dev
            - elinks

before_install:
    - perl -V

install: true

script:
    - ./autogen.sh --with-proxy --with-bot --with-perl=module --with-otr=no --prefix=$HOME/irssi-build
    - cat config.log
    - make
    - make install

notifications:
    irc:
        channels:
            - "irc.freenode.net#irssi"
        template:
            - "%{repository} (%{commit}: %{author}): %{message}"
            - "Build details : %{build_url}"
        on_success: always
        on_failure: always
        use_notice: true
        skip_join: true
